image:
  tag: $ARGOCD_APP_REVISION

springprofile: int

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: "traceability.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - "traceability.int.demo.catena-x.net"
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret

mailserver:
  password: <path:traceability-foss-backend/data/int#mailserverPassword>
