#
#  Copyright (c) 2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#

#########################
# Global Values configuration     #
#########################
global:
  enablePrometheus: false
  enableGrafana: false

#########################
# Frontend Chart Values configuration     #
#########################
frontend:
  image:
    repository: ghcr.io/catenax-ng/tx-traceability-foss
    tag: $ARGOCD_APP_REVISION
    CATENAX_PORTAL_API_URL: '<path:traceability-foss/data/e2e/b/frontend#catenax_portal_api_url>'
    CATENAX_PORTAL_KEYCLOAK_URL: '<path:traceability-foss/data/e2e/b/frontend#catenax_portal_keycloak_url>'
    CATENAX_PORTAL_BACKEND_DOMAIN: '<path:traceability-foss/data/e2e/b/frontend#catenax_portal_backend_domain>'
    CATENAX_PORTAL_URL: '<path:traceability-foss/data/e2e/b/frontend#catenax_portal_url>'
    CATENAX_PORTAL_CLIENT_ID: '<path:traceability-foss/data/e2e/b/frontend#catenax_portal_client_id>'

  nameOverride: "tx-frontend-e2e-b"
  fullnameOverride: "tx-frontend-e2e-b"

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: "traceability-portal-e2e-b.dev.demo.catena-x.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "traceability-portal-e2e-b.dev.demo.catena-x.net"
        secretName: "traceability-portal-e2e-b.dev.demo.catena-x.net-tls"

#########################
# Backend Chart Values configuration     #
#########################
backend:
  image:
    repository: ghcr.io/catenax-ng/tx-traceability-foss
    tag: $ARGOCD_APP_REVISION

  nameOverride: "tx-backend-e2e-b"
  fullnameOverride: "tx-backend-e2e-b"

  podSecurityContext:
    runAsUser: 10001
    seccompProfile:
      type: RuntimeDefault

  # Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
  # @url: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 3000
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false

  # Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
  # @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits
  resources:
    limits:
      cpu: 1500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  springprofile: e2e-b

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - host: "traceability-e2e-b.dev.demo.catena-x.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "traceability-e2e-b.dev.demo.catena-x.net"
        secretName: tls-secret

  traceability:
    bpn: "BPNL00000003CNKC"
    url: "https://traceability-e2e-b.dev.demo.catena-x.net"

  datasource:
    url: jdbc:postgresql://tx-backend-postgresql-e2e-b:5432/trace
    username: trace
    password: <path:traceability-foss/data/dev/database#tracePassword>

  oauth2:
    clientId: <path:traceability-foss/data/int/keycloak/oauth2#clientId>
    clientSecret: <path:traceability-foss/data/int/keycloak/oauth2#clientSecret>
    clientTokenUri: "https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
    jwkSetUri: "https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs"
    resourceClient: "Cl17-CX-Part"

  edc:
    apiKey: "<path:traceability-foss/data/dev/edc/controlplane#edc.api.control.auth.apikey.value>"
    providerUrl: "https://tx-edc-consumer-e2e-b-controlplane.dev.demo.catena-x.net"
    callbackUrl: "http://tx-irs-e2e-b:8181/internal/endpoint-data-reference"
    callbackUrlEdcClient: "https://traceability-e2e-b.dev.demo.catena-x.net/api/internal/endpoint-data-reference"
    dataEndpointUrl: "https://tx-edc-consumer-e2e-b-controlplane.dev.demo.catena-x.net/management"

  discoveryfinder:
    baseUrl: "https://tracex-discovery-mock-e2e-b.dev.demo.catena-x.net/api/administration/connectors/discovery/search"

  irs:
    baseUrl: "https://tx-irs-e2e-b.dev.demo.catena-x.net"
  registry:
    urlWithPath: "https://trace-x-registry-e2e-b.dev.demo.catena-x.net/semantics/registry/api/v3.0"
  portal:
    baseUrl: "https://portal-backend.dev.demo.catena-x.net/api"

  config:
    allowedCorsOriginFirst: "http://localhost:4200/"
    allowedCorsOriginSecond: "https://traceability-portal-e2e-b.dev.demo.catena-x.net/"

  dependencies:
    enabled: true
    irs: "tx-irs-e2e-b"  # <irs-helm.nameOverride>
    edc: "tx-edc-consumer-e2e-b"  # <tractusx-connector.nameOverride

#########################
# PG Admin configuration     #
#########################
pgadmin4:
  nameOverride: "tx-pgadmin-e2e-b"
  fullnameOverride: "tx-pgadmin-e2e-b"
  enabled: true
  strategy:
    type: Recreate
  networkPolicy:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - host: tx-pgadmin-e2e-b.dev.demo.catena-x.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - tx-pgadmin-e2e-b.dev.demo.catena-x.net
        secretName: tls-secret
  env:
    email: pgadmin4@trace.foss
    password: "<path:traceability-foss/data/dev/database#pgadminPassword>"
    variables:
      - name: PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED
        value: "False"
  resources:
    limits:
      cpu: 768m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 256Mi

#########################
# Postgres configuration     #
#########################
postgresql:
  enabled: true

  nameOverride: "tx-backend-postgresql-e2e-b"
  fullnameOverride: "tx-backend-postgresql-e2e-b"

  auth:
    postgresPassword: "<path:traceability-foss/data/dev/database#postgresPassword>"
    password: "<path:traceability-foss/data/dev/database#tracePassword>"
    database: "trace"
    username: "trace"

#########################
# IRS configuration     #
#########################
irs-helm:
  bpn: BPNL00000003CML1
  enabled: true

  nameOverride: "tx-irs-e2e-b"
  fullnameOverride: "tx-irs-e2e-b"

  namespace: product-traceability-foss

  springprofile: dev

  irsUrl: "https://tx-irs-e2e-b.dev.demo.catena-x.net"

  ingress:
    enabled: true
    hosts:
      - host: "tx-irs-e2e-b.dev.demo.catena-x.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "tx-irs-e2e-b.dev.demo.catena-x.net"
        secretName: tls-secret
  digitalTwinRegistry:
    type: decentral
    descriptorEndpoint: https://trace-x-registry-e2e-b.dev.demo.catena-x.net/semantics/registry/api/v3.0/shell-descriptors/{aasIdentifier}
    shellLookupEndpoint: https://trace-x-registry-e2e-b.dev.demo.catena-x.net/semantics/registry/api/v3.0/lookup/shells?assetIds={assetIds}
    discoveryFinderUrl: https://tracex-discovery-mock-e2e-b.dev.demo.catena-x.net/irs/api/administration/connectors/discovery/search

  semanticshub:
    url: https://semantics.int.demo.catena-x.net/hub/api/v1/models
  bpdm:
    url: https://partners-pool.int.demo.catena-x.net

  minioUser: <path:traceability-foss/data/dev/minio#user>
  minioPassword: <path:traceability-foss/data/dev/minio#password>
  minioUrl: http://tracex-irs-minio-e2e-b:9000

  keycloak:
    oauth2:
      clientId: <path:traceability-foss/data/int/keycloak/oauth2#clientId>
      clientSecret: <path:traceability-foss/data/int/keycloak/oauth2#clientSecret>
      clientTokenUri: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
      jwkSetUri: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs

  edc:
    callbackurl: http://tx-irs-e2e-b:8181/internal/endpoint-data-reference
    catalog:
      cache:
        enabled: "false"
    controlplane:
      endpoint:
        statesuffix: /state
        data: https://tx-edc-consumer-e2e-b-controlplane.dev.demo.catena-x.net/management
      apikey:
        secret: <path:traceability-foss/data/dev/edc/controlplane#edc.api.control.auth.apikey.value>


  minio:
    nameOverride: "tracex-irs-minio-e2e-b"
    fullnameOverride: "tracex-irs-minio-e2e-b"
    serviceAccount:
      create: false
    rootUser: <path:traceability-foss/data/dev/minio#user>
    rootPassword: <path:traceability-foss/data/dev/minio#password>

###################################
# EDC Consumer configuration  #
###################################
tractusx-connector:
  fullnameOverride: "tx-edc-consumer-e2e-b"
  nameOverride: "tx-edc-consumer-e2e-b"
  enabled: true
  install:
    postgresql: false
    vault: false
  participant:
    id: BPNL00000003CML1

  controlplane:
    ingresses:
      - enabled: true
        hostname: "tx-edc-consumer-e2e-b-controlplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret
    ssi:
      miw:
        url: <path:traceability-foss/data/dev/edc/wallet#ssi.miw.url>
        authorityId: <path:traceability-foss/data/dev/edc/wallet#ssi.miw.authorityId>
      oauth:
        tokenurl: <path:traceability-foss/data/dev/edc/wallet#ssi.oauth.tokenurl>
        client:
          id: <path:traceability-foss/data/dev/edc/wallet#ssi.oauth.client.id>
          secretAlias: edc-miw-keycloak-secret

    endpoints:
      # -- default api for health checks, should not be added to any ingress
      default:
        port: 8080
        path: /api
      # -- data management api, used by internal users, can be added to an ingress and must not be internet facing
      management:
        port: 8081
        path: /management
        # -- authentication key, must be attached to each 'X-Api-Key' request header
        authKey: <path:traceability-foss/data/dev/edc/controlplane#edc.api.control.auth.apikey.value>
      # -- control api, used for internal control calls. can be added to the internal ingress, but should probably not
      control:
        port: 8083
        path: /control
      # -- ids api, used for inter connector communication and must be internet facing
      protocol:
        port: 8084
        path: /api/v1/dsp
      # -- metrics api, used for application metrics, must not be internet facing
      metrics:
        port: 9090
        path: /metrics
      # -- observability api with unsecured access, must not be internet facing
      observability:
        port: 8085
        # -- observability api, provides /health /readiness and /liveness endpoints
        path: /observability
        # -- allow or disallow insecure access, i.e. access without authentication
        insecure: true
    internationalDataSpaces:
      id: TXDC
      description: Tractus-X Eclipse IDS Data Space Connector
      title: ""
      maintainer: ""
      curator: ""
      catalogId: TXDC-Catalog

    # Explicitly declared url for reaching the ids api (e.g. if ingresses not used)
    url:
      ids: ""

    resources:
      limits:
        cpu: 2000m
        memory: 3Gi
      requests:
        cpu: 100m
        memory: 3Gi

  dataplane:
    ingresses:
      - enabled: true
        hostname: "tx-edc-consumer-e2e-b-dataplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret

    endpoints:
      default:
        port: 8080
        path: /api
      public:
        port: 8081
        path: /api/public
      control:
        port: 8083
        path: /api/dataplane/control
      observability:
        port: 8085
        path: /observability
        insecure: true
      metrics:
        port: 9090
        path: /metrics
    # Explicitly declared url for reaching the public api (e.g. if ingresses not used)
    url:
      public: ""

    resources:
      limits:
        cpu: 2000m
        memory: 3Gi
      requests:
        cpu: 100m
        memory: 3Gi

  ## currently we need to provide a url but is not used anywhere
  # URL where the EndpointDataReference callback will be sent to
  backendService:
    httpProxyTokenReceiverUrl: "https://traceability-e2e-b.dev.demo.catena-x.net/api/callback/endpoint-data-reference"
    # Files system has to be set to writeable for now since controlplane relies on temporary files to write SSI related things to
  securityContext:
    readOnlyRootFilesystem: false
  ################################
  # EDC Vault Configuration #
  ################################
  vault:
    hashicorp:
      url: "https://vault.demo.catena-x.net"
      token: "<path:traceability-foss/data/dev/edc#edc.vault.hashicorp.token>"
      timeout: 30
      healthCheck:
        enabled: true
        standbyOk: true
      paths:
        secret: /v1/traceability-foss
        health: /v1/sys/health
    secretNames:
      transferProxyTokenSignerPrivateKey: daps-cert-edc-e2e-b-consumer-private
      transferProxyTokenSignerPublicKey: daps-cert-edc-e2e-b-consumer-public
      transferProxyTokenEncryptionAesKey: token-signer-aes-key

  ##################################
  # EDC Postgres Configuration #
  ##################################
  postgresql:
    enabled: true
    auth:
      username: "<path:traceability-foss/data/dev/edc/database#user>"
      password: "<path:traceability-foss/data/dev/edc/database#password>"
    username: "<path:traceability-foss/data/dev/edc/database#user>"
    password: "<path:traceability-foss/data/dev/edc/database#password>"
    jdbcUrl: "jdbc:postgresql://tx-edc-consumer-postgresql-e2e-b-hl:5432/edc"

###################################
# EDC Postgres Configuration #
###################################
edc-postgresql:
  nameOverride: "tx-edc-consumer-postgresql-e2e-b"
  fullnameOverride: "tx-edc-consumer-postgresql-e2e-b"
  enabled: true
  auth:
    database: edc
    username: <path:traceability-foss/data/dev/edc/database#user>
    postgresPassword: <path:traceability-foss/data/dev/edc/database#password>
    password: <path:traceability-foss/data/dev/edc/database#password>
