#
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

#########################
# Global Values configuration     #
#########################
global:
  enablePrometheus: false
  enableGrafana: false

#########################
# Frontend Chart Values configuration     #
#########################
frontend:
  image:
    tag: $ARGOCD_APP_REVISION
    CATENAX_PORTAL_API_URL: 'https://traceability-int-b.int.demo.catena-x.net/api'
    CATENAX_PORTAL_KEYCLOAK_URL: 'https://centralidp.int.demo.catena-x.net/auth'
    CATENAX_PORTAL_BACKEND_DOMAIN: 'catena-x.net'
    CATENAX_PORTAL_URL: 'https://portal.int.demo.catena-x.net/'

  nameOverride: "traceability-foss-int-b-frontend"
  fullnameOverride: "traceability-foss-int-b-frontend"

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: "traceability-portal-int-b.int.demo.catena-x.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "traceability-portal-int-b.int.demo.catena-x.net"
        secretName: "traceability-portal-int-b.int.demo.catena-x.net-tls"

#########################
# Backend Chart Values configuration     #
#########################
backend:
  image:
    repository: ghcr.io/catenax-ng/tx-traceability-foss
    tag: $ARGOCD_APP_REVISION

  nameOverride: "traceability-foss-backend-int-b"
  fullnameOverride: "traceability-foss-backend-int-b"

  podSecurityContext:
    runAsUser: 10001
    seccompProfile:
      type: RuntimeDefault

  # Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
  # @url: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 3000
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false

  # Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
  # @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

  springprofile: int-b

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - host: "traceability-int-b.int.demo.catena-x.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "traceability-int-b.int.demo.catena-x.net"
        secretName: tls-secret

  traceability:
    bpn: "BPNL000000BTRACE"
    url: "https://traceability-int-b.int.demo.catena-x.net"

  datasource:
    url: jdbc:postgresql://traceability-foss-backend-int-a-postgresql:5432/trace
    username: trace
    password: <path:traceability-foss/data/int/database#tracePassword>

  oauth2:
    clientId: <path:traceability-foss/data/int/keycloak/oauth2#clientId>
    clientSecret: <path:traceability-foss/data/int/keycloak/oauth2#clientSecret>
    clientTokenUri: "https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
    jwkSetUri: "https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs"
    resourceClient: "Cl17-CX-Part"

  edc:
    apiKey: "<path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>"
    providerUrl: "https://tracex-consumer-controlplane-int-b.int.demo.catena-x.net"
    callbackUrl: ""
    callbackUrlEdcClient: ""
    dataEndpointUrl: ""

  discoveryfinder:
    baseUrl: ""
#########################
# PG Admin configuration     #
#########################
pgadmin4:
  enabled: true
  strategy:
    type: Recreate
  networkPolicy:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - host: tracex-pgadmin4-int-b.int.demo.catena-x.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - tracex-pgadmin4-int-b.int.demo.catena-x.net
        secretName: tls-secret
  env:
    email: pgadmin4@trace.foss
    password: "<path:traceability-foss/data/int/database#pgadminPassword>"
    variables:
      - name: PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED
        value: "False"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

#########################
# Postgres configuration     #
#########################
postgresql:
  enabled: true

  nameOverride: "traceability-foss-backend-int-b-postgresql"
  fullnameOverride: "traceability-foss-backend-int-b-postgresql"

  auth:
    postgresPassword: "<path:traceability-foss/data/int/database#postgresPassword>"
    password: "<path:traceability-foss/data/int/database#tracePassword>"
    database: "trace"
    username: "trace"

#########################
# IRS configuration     #
#########################
irs-helm:
  enabled: true
  bpn: BPNL000000BTRACE

  nameOverride: "tracex-irs-int-b"
  fullnameOverride: "tracex-irs-int-b"

  namespace: product-traceability-foss

  springprofile: dev

  irsUrl: "https://tracex-irs-int-b.int.demo.catena-x.net"

  ingress:
    enabled: true
    hosts:
      - host: "tracex-irs-int-b.int.demo.catena-x.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "tracex-irs-int-b.dev.demo.catena-x.net"
        secretName: tls-secret
  # is dtr url correct ?
  digitalTwinRegistry:
    url: https://trace-x-registry-int-b.int.demo.catena-x.net/semantics/registry
  semanticshub:
    url: https://semantics.int.demo.catena-x.net/hub/api/v1/models
  bpdm:
    url: https://partners-pool.int.demo.catena-x.net

  minioUser: <path:traceability-foss/data/int/minio#user>
  minioPassword: <path:traceability-foss/data/int/minio#password>
  minioUrl: http://tracex-irs-minio-int-b:9000

  keycloak:
    oauth2:
      clientId: <path:traceability-foss/data/int/keycloak/oauth2#clientId>
      clientSecret: <path:traceability-foss/data/int/keycloak/oauth2#clientSecret>
      clientTokenUri: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
      jwkSetUri: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs

  edc:
    controlplane:
      endpoint:
        data: http://tracex-consumer-controlplane-int-b:8181/data
      apikey:
        secret: <path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>

  minio:
    nameOverride: "tracex-irs-minio-int-b"
    fullnameOverride: "tracex-irs-minio-int-b"
    serviceAccount:
      create: false
    rootUser: <path:traceability-foss/data/int/minio#user>
    rootPassword: <path:traceability-foss/data/int/minio#password>

###################################
# IRS EDC Consumer configuration  #
###################################
irs-edc-consumer:
  enabled: true

  postgresql:
    nameOverride: "tracex-consumer-edc-postgresql-int-b"
    fullnameOverride: "tracex-consumer-edc-postgresql-int-b"

    namespace: product-traceability-foss

    securityContext:
      readOnlyRootFilesystem: false

    auth:
      postgresPassword: <path:traceability-foss/data/int/edc/database#password>
      username: <path:traceability-foss/data/int/edc/database#user>
      password: <path:traceability-foss/data/int/edc/database#password>
      database: "edc"

  # Values for consumer edc-controlplane.
  edc-controlplane:
    nameOverride: "tracex-consumer-controlplane-int-b"
    fullnameOverride: "tracex-consumer-controlplane-int-b"

    namespace: product-traceability-foss

    image:
      tag: "0.3.0"

    ingresses:
      - enabled: true
        hostname: "tracex-consumer-controlplane-int-b.int.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        className: "nginx"
        tls:
          - hosts:
              - "tracex-consumer-controlplane-int-b.int.demo.catena-x.net"
            secretName: tls-secret

    resources:
      limits:
        cpu: 600
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi

    logging:
      # -- EDC logging.properties configuring the [java.util.logging subsystem](https://docs.oracle.com/javase/7/docs/technotes/guides/logging/overview.html#a1.8)
      properties: |-
        .level=INFO
        org.eclipse.edc.level=INFO
        net.catenax.edc.hashicorpvault.level=INFO
        handlers=java.util.logging.ConsoleHandler
        java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
        java.util.logging.ConsoleHandler.level=INFO
        java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n

    edc:
      postgresql:
        password: <path:traceability-foss/data/dev/edc/database#password>
      transfer:
        proxy:
          token:
            verifier:
              publickey:
                alias: daps-cert-int-b
            signer:
              privatekey:
                alias: daps-cert-key-int-b
      api:
        auth:
          key: <path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>
      controlplane:
        url: "https://tracex-consumer-controlplane-int-b.int.demo.catena-x.net"
      dataplane:
        url: "https://tracex-consumer-dataplane-int-b.int.demo.catena-x.net"


    configuration:
      # -- EDC configuration.properties configuring aspects of the [eclipse-dataspaceconnector](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector)
      properties: |-

        edc.receiver.http.dynamic.endpoint=https://traceability-int-b.int.demo.catena-x.net/api/callback/endpoint-data-reference
        edc.dataplane.selector.consumer.url=http://tracex-consumer-dataplane-int-b:9999/api/dataplane/control
        edc.oauth.client.id=78:6A:2B:DB:36:6A:3A:42:99:7F:A3:20:AE:77:7A:4A:19:D6:E0:8F:keyid:78:6A:2B:DB:36:6A:3A:42:99:7F:A3:20:AE:77:7A:4A:19:D6:E0:8F
        edc.oauth.certificate.alias=daps-cert-int-b
        edc.oauth.private.key.alias=daps-cert-key-int-b
        edc.oauth.provider.jwks.url=https://daps1.int.demo.catena-x.net/.well-known/jwks.json
        edc.oauth.token.url=https://daps1.int.demo.catena-x.net/token
        edc.vault.hashicorp.url=https://vault.demo.catena-x.net
        edc.vault.hashicorp.token=<path:traceability-foss/data/int/edc#edc.vault.hashicorp.token>
        edc.vault.hashicorp.api.secret.path=/v1/traceability-foss
        edc.data.encryption.keys.alias=edc-data-encryption-keys-alias
        edc.data.encryption.algorithm=NONE

        edc.datasource.asset.url=jdbc:postgresql://tracex-consumer-edc-postgresql-int-b-hl:5432/edc
        edc.datasource.asset.user=<path:traceability-foss/data/int/edc/database#user>
        edc.datasource.asset.password=<path:traceability-foss/data/int/edc/database#password>

        edc.datasource.contractdefinition.url=jdbc:postgresql://tracex-consumer-edc-postgresql-int-b-hl:5432/edc
        edc.datasource.contractdefinition.user=<path:traceability-foss/data/int/edc/database#user>
        edc.datasource.contractdefinition.password=<path:traceability-foss/data/int/edc/database#password>

        edc.datasource.contractnegotiation.url=jdbc:postgresql://tracex-consumer-edc-postgresql-int-b-hl:5432/edc
        edc.datasource.contractnegotiation.user=<path:traceability-foss/data/int/edc/database#user>
        edc.datasource.contractnegotiation.password=<path:traceability-foss/data/int/edc/database#password>

        edc.datasource.policy.url=jdbc:postgresql://tracex-consumer-edc-postgresql-int-b-hl:5432/edc
        edc.datasource.policy.user=<path:traceability-foss/data/int/edc/database#user>
        edc.datasource.policy.password=<path:traceability-foss/data/int/edc/database#password>

        edc.datasource.transferprocess.url=jdbc:postgresql://tracex-consumer-edc-postgresql-int-b-hl:5432/edc
        edc.datasource.transferprocess.user=<path:traceability-foss/data/int/edc/database#user>
        edc.datasource.transferprocess.password=<path:traceability-foss/data/int/edc/database#password>

  # Values for consumer edc-dataplane.
  edc-dataplane:
    nameOverride: "tracex-consumer-dataplane-int-b"
    fullnameOverride: "tracex-consumer-dataplane-int-b"

    namespace: product-traceability-foss

    securityContext:
      readOnlyRootFilesystem: false

    image:
      tag: "0.3.0"

    ingresses:
      - enabled: true
        hostname: "tracex-consumer-dataplane-int-b.int.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          - hosts:
              - "tracex-consumer-dataplane-int-b.int.demo.catena-x.net"
            secretName: tls-secret

    resources:
      limits:
        cpu: 600m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi

    logging:
      # -- EDC logging.properties configuring the [java.util.logging subsystem](https://docs.oracle.com/javase/7/docs/technotes/guides/logging/overview.html#a1.8)
      properties: |-
        .level=INFO
        org.eclipse.edc.level=INFO
        net.catenax.edc.hashicorpvault.level=INFO
        handlers=java.util.logging.ConsoleHandler
        java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
        java.util.logging.ConsoleHandler.level=INFO
        java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n

    configuration:
      properties: |-
        edc.api.auth.key=<path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>
        edc.dataplane.token.validation.endpoint=http://tracex-consumer-controlplane-int-b:8182/validation/token

        edc.oauth.client.id=78:6A:2B:DB:36:6A:3A:42:99:7F:A3:20:AE:77:7A:4A:19:D6:E0:8F:keyid:78:6A:2B:DB:36:6A:3A:42:99:7F:A3:20:AE:77:7A:4A:19:D6:E0:8F
        edc.oauth.certificate.alias=daps-cert-int-b
        edc.oauth.private.key.alias=daps-cert-key-int-b

        edc.oauth.provider.jwks.url=https://daps1.int.demo.catena-x.net/.well-known/jwks.json
        edc.oauth.token.url=https://daps1.int.demo.catena-x.net/token

        edc.vault.hashicorp.url=https://vault.demo.catena-x.net
        edc.vault.hashicorp.token=<path:traceability-foss/data/int/edc#edc.vault.hashicorp.token>
        edc.vault.hashicorp.api.secret.path=/v1/traceability-foss

