{{ if .Values.install.edc.vault }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.vault.secret.name  | toString | quote }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
type: Opaque
data:
  dapsCert: {{ .Files.Get "certs/edc.crt" | b64enc }}
  dapsKey: {{ .Files.Get "certs/edc.key" | b64enc }}
  dataEncryption: {{ .Values.config.vault.secret.dataEncryptionValue | toString | quote | b64enc }}

{{ end }}
