################################################################################
# Copyright (c) 2022, 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
# Copyright (c) 2022, 2023 ZF Friedrichshafen AG
# Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

spring:
  flyway:
    locations: /db/migration,/db/testdata-tier2
    placeholders:
      assetAsBuiltId01: "'urn:uuid:6ec3f1db-2798-454b-a73f-0d21a8966c77'"
      assetAsBuiltId02: "'urn:uuid:132fd82b-caab-476b-b453-b7273a4c7c01'"
      assetAsBuiltId03: "'urn:uuid:c0edce5c-546f-4e79-9d86-a4cb7ca7b900'"
      assetAsBuiltId04: "'urn:uuid:6b739098-dec0-4726-b5cb-e8cd5091a9f2'"
      assetAsBuiltId05: "'urn:uuid:0f440d8a-4c74-417b-b217-bbcd1aebdd8d'"
      assetAsBuiltId06: "'urn:uuid:b3707747-59f2-46f3-98c7-a5a77fdb2d2f'"
      assetAsBuiltId07: "'urn:uuid:c032bf1f-38a6-4a73-b64c-02ce0853dc42'"
      assetAsBuiltId08: "'urn:uuid:6d547770-01f5-4618-b055-4f0b86e2924f'"
      assetAsBuiltId09: "'urn:uuid:c09aa1f9-c8f4-4e92-935a-ea64ac703e33'"
      assetAsBuiltId10: "'urn:uuid:135249bf-2a52-499f-a686-1377ecc38ab7'"

      assetAsPlannedId01: "'urn:uuid:e97699c1-89c1-474b-8a92-c3a887c6b4c0'"
      assetAsPlannedId02: "'urn:uuid:78e5523d-73b6-4770-b5f5-5ea314c33674'"
      assetAsPlannedId03: "'urn:uuid:233fda23-3d10-454e-abec-6cb29813bcd5'"
      assetAsPlannedId04: "'urn:uuid:cce342a3-910f-4802-b8a2-c37c59344cf2'"
      assetAsPlannedId05: "'urn:uuid:daa579ab-23e5-407b-b2cf-0b24ff400fec'"
      assetAsPlannedId06: "'urn:uuid:25f34391-f73c-49f7-bcf5-95c1c8de4f2e'"
      assetAsPlannedId07: "'urn:uuid:94be6a68-f8f0-47e2-9a23-a37d15c0c680'"
      assetAsPlannedId08: "'urn:uuid:2af628f6-522f-4eb9-aeff-2e52ed619548'"
      assetAsPlannedId09: "'urn:uuid:e266a50e-174d-4e73-9158-3a98eac1ad58'"
      assetAsPlannedId10: "'urn:uuid:c8d6ebd6-f205-430f-93d1-d09a1540d307'"

      alertSentId1: 1
      alertSentId2: 2

      alertReceivedId1: 11

      alertNotificationSentId1: "'4939c189-b75d-4647-94cb-a75b83a92313'"
      alertNotificationSentId2: "'a15583ac-101e-44e0-9fba-33ceaa4d3540'"

      alertNotificationReceivedId1: "'e3de866d-044b-4db9-9349-841365189a9b'"

      investigationSentId1: 1
      investigationSentId2: 2

      investigationReceivedId1: 11

      investigationNotificationSentId1: "'7486286d-a098-4617-81ea-3015bc866a7e'"
      investigationNotificationSentId2a: "'94032934-8ec8-4f97-a38d-6b16d448cbfb'"
      investigationNotificationSentId2b: "'b5b4612e-6ed6-47c2-8f52-adefe3d5b99a'"

      investigationNotificationReceivedId1: "'0678b9c6-a9c4-4ff9-a5e2-c6cd19c5f8c6'"

