apiVersion: v2
name: traceability-foss-backend
description: A Helm chart for Traceability backend application
type: application
version: 2.3.15
appVersion: "2.3.15"
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
    condition: postgresql.enabled
  - name: pgadmin4
    repository: https://helm.runix.net
    version: 1.13.6
    condition: pgadmin4.enabled
  - name: irs-helm
    repository: https://eclipse-tractusx.github.io/item-relationship-service
    version: 4.2.1
    condition: irs-helm.enabled
  - name: irs-edc-consumer
    repository: https://catenax-ng.github.io/tx-item-relationship-service
    version: 1.0.2
    condition: irs-edc-consumer.enabled

