apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omejdn-server.fullname" . }}
  labels:
    {{- include "omejdn-server.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env.config }}
    {{ $key }}: "{{ $val }}"
  {{- end}}
  plugins.yml: |-
    ---
    plugins:
      admin_api:
      token_user_attributes:
        skip_access_token: false
        skip_id_token: false

  scope_mapping.yml: |-
    ---
    plugins:
    omejdn:read:
    - omejdn
    omejdn:write:
    - omejdn
    omejdn:admin:
    - omejdn
    profile:
    - name
    - family_name
    - given_name
    - middle_name
    - nickname
    - preferred_username
    - profile
    - picture
    - website
    - gender
    - birthdate
    - zoneinfo
    - locale
    - updated_at
    email:
    - email
    - email_verified
    address:
    - formatted
    - street_address
    - locality
    - region
    - postal_code
    - country
    phone:
    - phone_number
    - phone_number_verified
    idsc:IDS_CONNECTOR_ATTRIBUTES_ALL:
    - "@type"
    - "@context"
    - "securityProfile"
    - "referringConnector"



  omejdn.yml: |-
    ---
    issuer: https://{{ .Values.ingress.host }}
    front_url: https://{{ .Values.ingress.host }}
    bind_to: 0.0.0.0:4567
    environment: development
    openid: false
    default_audience: idsc:IDS_CONNECTORS_ALL
    accept_audience:
    - https://{{ .Values.ingress.host }}{{ .Values.ingress.rootPath }}
    - https://{{ .Values.ingress.host }}{{ .Values.ingress.rootPath }}token
    - idsc:IDS_CONNECTORS_ALL
    access_token:
     expiration: 3600
     algorithm: RS256
    id_token:
     expiration: 3600
     algorithm: RS256
    user_backend:
    - yaml
      
  
  {{- if .Values.omejdn.createDefaultAdmin }}
  clients.yml: |-
    ---
    - client_id: admin
      name: omejdn admin ui
      client_secret: secret@catenax!
      token_endpoint_auth_method: client_secret_post
      attributes:
      - key: omejdn
        value: admin
      redirect_uris:
      - https://example.org/callback01
      - https://example.org/callback02
      - https://oauth.pstmn.io/v1/callback
      - "/"
      scope:
      - omejdn:admin
      grant_types:
      - client_credentials
  {{- end }}
