apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.backend.namespace | default .Release.Namespace }}
  name: {{ include "traceability-foss-backend.fullname" . }}
  labels:
    {{- include "traceability-foss-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.backend.service.type }}
  ports:
    - port: {{ .Values.global.backend.service.port }}
      targetPort: {{ .Values.global.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "traceability-foss-backend.selectorLabels" . | nindent 4 }}
