---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edc-dataplane.fullname" . }}-configmap
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-dataplane.labels" . | nindent 4 }}
data:
  configuration.properties: |-
    web.http.default.port={{ .Values.edc.endpoints.default.port }}
    web.http.default.path={{ .Values.edc.endpoints.default.path }}
    web.http.public.port={{ .Values.edc.endpoints.public.port }}
    web.http.public.path={{ .Values.edc.endpoints.public.path }}
    web.http.control.port={{ .Values.edc.endpoints.control.port }}
    web.http.control.path={{ .Values.edc.endpoints.control.path }}
    edc.api.auth.key={{ .Values.edc.api.auth.key }}
    edc.receiver.http.endpoint=http://{{ .Release.Name }}-irs-aaswrapper:9192/callback/endpoint-data-reference
    edc.dataplane.token.validation.endpoint=http://{{ .Release.Name }}-edc-controlplane:8182/validation/token
    edc.vault.hashicorp.timeout.seconds=30
    edc.vault.hashicorp.health.check.enabled=true
    edc.vault.hashicorp.health.check.standby.ok=true
    {{- .Values.configuration.properties | nindent 4 }}

  opentelemetry.properties: |-
    {{- .Values.opentelemetry.properties | nindent 4 }}

  logging.properties: |-
    {{- .Values.logging.properties | nindent 4 }}