apiVersion: v2
name: product-traceability-foss-backend
description: A Helm chart for Traceability backend application
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
    condition: postgresql.enabled
  - name: pgadmin4
    repository: https://helm.runix.net
    version: 1.13.6
    condition: pgadmin4.enabled
  - name: irs-helm
    repository: https://catenax-ng.github.io/tx-item-relationship-service
    version: 2.1.0
    condition: irs-helm.enabled
