image:
  tag: $ARGOCD_APP_REVISION

nameOverride: "product-traceability-foss-test-backend"
fullnameOverride: "product-traceability-foss-test-backend"

springprofile: dev

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  hosts:
    - host: "traceability-test.dev.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - "traceability-test.dev.demo.catena-x.net"
      secretName: tls-secret

traceability:
  bpn: "BPNL00000003AYRE"

datasource:
  url: jdbc:postgresql://tracex-backend-test-postgresql-hl:5432/trace
  username: trace
  password: <path:traceability-foss/data/dev/database#tracePassword>

oauth2:
  clientId: <path:traceability-foss/data/int/keycloak/oauth2#clientId>
  clientSecret: <path:traceability-foss/data/int/keycloak/oauth2#clientSecret>
  clientTokenUri: "https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
  jwkSetUri: "https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs"
  resourceClient: "Cl17-CX-Part"

edc:
  apiKey: "<path:traceability-foss/data/dev/edc/controlplane#edc.api.control.auth.apikey.value>"

postgresql:
  enabled: true

  nameOverride: "tracex-backend-test-postgresql"
  fullnameOverride: "tracex-backend-test-postgresql"

  auth:
    postgresPassword: "<path:traceability-foss/data/dev/database#postgresPassword>"
    password: "<path:traceability-foss/data/dev/database#tracePassword>"
    database: "trace"
    username: "trace"

pgadmin4:
  enabled: true
  strategy:
    type: Recreate
  networkPolicy:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - host: tracex-pgadmin4-test.dev.demo.catena-x.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - tracex-pgadmin4-test.dev.demo.catena-x.net
        secretName: tls-secret
  env:
    email: pgadmin4@trace.foss
    password: "<path:traceability-foss/data/dev/database#pgadminPassword>"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 256m
      memory: 512Mi

global:
  enablePrometheus: false
  enableGrafana: false

#########################
# IRS configuration     #
#########################
irs-helm:
  enabled: true

  nameOverride: "tracex-test-irs"
  fullnameOverride: "tracex-test-irs"

  namespace: product-traceability-foss

  springprofile: dev

  irsUrl: "https://tracex-irs-test.dev.demo.catena-x.net"

  ingress:
    enabled: true
    hosts:
      - host: "tracex-irs-test.dev.demo.catena-x.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "tracex-irs-test.dev.demo.catena-x.net"
        secretName: tls-secret
  digitalTwinRegistry:
    url: https://trace-x-registry.dev.demo.catena-x.net
  semanticsHub:
    url: https://semantics.int.demo.catena-x.net/hub/api/v1
  bpdm:
    url: https://catenax-bpdm-int.demo.catena-x.net/v1

  minioUser: <path:traceability-foss/data/dev/minio#user>
  minioPassword: <path:traceability-foss/data/dev/minio#password>
  minioUrl: http://tracex-test-irs-minio:9000

  keycloak:
    oauth2:
      clientId: <path:traceability-foss/data/int/keycloak/oauth2#clientId>
      clientSecret: <path:traceability-foss/data/int/keycloak/oauth2#clientSecret>
      clientTokenUri: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
      jwkSetUri: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs

  edc:
    controlplane:
      endpoint:
        data: http://tracex-test-consumer-controlplane:8181/data
      apikey:
        secret: <path:traceability-foss/data/dev/edc/controlplane#edc.api.control.auth.apikey.value>

  minio:
    nameOverride: "tracex-test-irs-minio"
    fullnameOverride: "tracex-test-irs-minio"
    rootUser: <path:traceability-foss/data/dev/minio#user>
    rootPassword: <path:traceability-foss/data/dev/minio#password>

###################################
# IRS EDC Consumer configuration  #
###################################
irs-edc-consumer:
  enabled: true

  postgresql:
    nameOverride: "tracex-test-consumer-edc-postgresql"
    fullnameOverride: "tracex-test-consumer-edc-postgresql"

    namespace: product-traceability-foss

    auth:
      postgresPassword: <path:traceability-foss/data/dev/edc/database#password>
      username: <path:traceability-foss/data/dev/edc/database#user>
      password: <path:traceability-foss/data/dev/edc/database#password>
      database: "edc"

  # Values for consumer edc-controlplane.
  edc-controlplane:
    nameOverride: "tracex-test-consumer-controlplane"
    fullnameOverride: "tracex-test-consumer-controlplane"

    namespace: product-traceability-foss

    image:
      tag: "0.1.2"

    ingresses:
      - enabled: true
        hostname: "tracex-test-consumer-controlplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - ids
          - data
        className: "nginx"
        tls:
          - hosts:
              - "tracex-test-consumer-controlplane.dev.demo.catena-x.net"
            secretName: tls-secret

    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 256m
        memory: 2Gi

    logging:
      # -- EDC logging.properties configuring the [java.util.logging subsystem](https://docs.oracle.com/javase/7/docs/technotes/guides/logging/overview.html#a1.8)
      properties: |-
        .level=INFO
        org.eclipse.dataspaceconnector.level=INFO
        net.catenax.edc.hashicorpvault.level=INFO
        handlers=java.util.logging.ConsoleHandler
        java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
        java.util.logging.ConsoleHandler.level=INFO
        java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n

    configuration:
      # -- EDC configuration.properties configuring aspects of the [eclipse-dataspaceconnector](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector)
      properties: |-
        edc.api.auth.key=<path:traceability-foss/data/dev/edc/controlplane#edc.api.control.auth.apikey.value>
        ids.webhook.address=https://tracex-test-consumer-controlplane.dev.demo.catena-x.net

        edc.ids.id=urn:connector:edc-consumer-controlplane
        edc.ids.catalog.id=urn:catalog:default
        edc.ids.endpoint=https://tracex-test-consumer-controlplane.dev.demo.catena-x.net/api/v1/ids
        edc.ids.endpoint.audience=https://tracex-test-consumer-controlplane.dev.demo.catena-x.net/api/v1/ids/data

        edc.receiver.http.endpoint=http://product-traceability-foss-backend-test-irs-aaswrapper:9192/callback/endpoint-data-reference

        edc.transfer.dataplane.sync.endpoint=http://tracex-test-consumer-dataplane:8185/api/public
        edc.transfer.proxy.endpoint=https://tracex-test-consumer-dataplane.dev.demo.catena-x.net/api/public/
        edc.transfer.proxy.token.signer.privatekey.alias=token-signer-cert-key-dev
        edc.transfer.proxy.token.verifier.publickey.alias=token-signer-cert-dev

        edc.dataplane.selector.consumer.url=http://tracex-test-consumer-dataplane:9999/api/dataplane/control
        edc.dataplane.selector.consumer.sourcetypes=HttpData
        edc.dataplane.selector.consumer.destinationtypes=HttpProxy
        edc.dataplane.selector.consumer.properties={ "publicApiUrl": "https://tracex-test-consumer-dataplane.dev.demo.catena-x.net/api/public/" }

        edc.oauth.client.id=3A:F4:B9:17:B7:01:BC:4D:A7:8B:58:19:18:30:7F:65:30:BB:90:62:keyid:3A:F4:B9:17:B7:01:BC:4D:A7:8B:58:19:18:30:7F:65:30:BB:90:62
        edc.oauth.public.key.alias=daps-cert-edc-test-provider-dev
        edc.oauth.private.key.alias=daps-cert-key-edc-test-provider-dev
        edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
        edc.oauth.provider.jwks.url=https://daps1.int.demo.catena-x.net/.well-known/jwks.json
        edc.oauth.token.url=https://daps1.int.demo.catena-x.net/token

        edc.vault.hashicorp.url=https://vault.demo.catena-x.net
        edc.vault.hashicorp.token=<path:traceability-foss/data/dev/edc#edc.vault.hashicorp.token>
        edc.vault.hashicorp.timeout.seconds=30
        edc.vault.hashicorp.health.check.enabled=true
        edc.vault.hashicorp.health.check.standby.ok=true
        edc.vault.hashicorp.api.secret.path=/v1/traceability-foss

        edc.data.encryption.keys.alias=edc-data-encryption-keys-alias
        edc.data.encryption.algorithm=NONE

        # Postgresql related configuration
        edc.datasource.asset.name=asset
        edc.datasource.asset.url=jdbc:postgresql://tracex-test-consumer-edc-postgresql-hl:5432/edc
        edc.datasource.asset.user=<path:traceability-foss/data/dev/edc/database#user>
        edc.datasource.asset.password=<path:traceability-foss/data/dev/edc/database#password>
        edc.datasource.contractdefinition.name=contractdefinition
        edc.datasource.contractdefinition.url=jdbc:postgresql://tracex-test-consumer-edc-postgresql-hl:5432/edc
        edc.datasource.contractdefinition.user=<path:traceability-foss/data/dev/edc/database#user>
        edc.datasource.contractdefinition.password=<path:traceability-foss/data/dev/edc/database#password>
        edc.datasource.contractnegotiation.name=contractnegotiation
        edc.datasource.contractnegotiation.url=jdbc:postgresql://tracex-test-consumer-edc-postgresql-hl:5432/edc
        edc.datasource.contractnegotiation.user=<path:traceability-foss/data/dev/edc/database#user>
        edc.datasource.contractnegotiation.password=<path:traceability-foss/data/dev/edc/database#password>
        edc.datasource.policy.name=policy
        edc.datasource.policy.url=jdbc:postgresql://tracex-test-consumer-edc-postgresql-hl:5432/edc
        edc.datasource.policy.user=<path:traceability-foss/data/dev/edc/database#user>
        edc.datasource.policy.password=<path:traceability-foss/data/dev/edc/database#password>
        edc.datasource.transferprocess.name=transferprocess
        edc.datasource.transferprocess.url=jdbc:postgresql://tracex-test-consumer-edc-postgresql-hl:5432/edc
        edc.datasource.transferprocess.user=<path:traceability-foss/data/dev/edc/database#user>
        edc.datasource.transferprocess.password=<path:traceability-foss/data/dev/edc/database#password>

  # Values for consumer edc-dataplane.
  edc-dataplane:
    nameOverride: "tracex-test-consumer-dataplane"
    fullnameOverride: "tracex-test-consumer-dataplane"

    namespace: product-traceability-foss

    image:
      tag: "0.1.2"

    ingresses:
      - enabled: true
        hostname: "tracex-test-consumer-dataplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          - hosts:
              - "tracex-test-consumer-dataplane.dev.demo.catena-x.net"
            secretName: tls-secret

    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 256m
        memory: 512Mi

    logging:
      # -- EDC logging.properties configuring the [java.util.logging subsystem](https://docs.oracle.com/javase/7/docs/technotes/guides/logging/overview.html#a1.8)
      properties: |-
        .level=INFO
        org.eclipse.dataspaceconnector.level=INFO
        net.catenax.edc.hashicorpvault.level=INFO
        handlers=java.util.logging.ConsoleHandler
        java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
        java.util.logging.ConsoleHandler.level=INFO
        java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n

    configuration:
      properties: |-
        edc.api.auth.key=<path:traceability-foss/data/dev/edc/controlplane#edc.api.control.auth.apikey.value>

        edc.dataplane.token.validation.endpoint=http://tracex-test-consumer-controlplane:8182/validation/token

        edc.receiver.http.endpoint=http://product-traceability-foss-backend-test-irs-aaswrapper:9192/callback/endpoint-data-reference

        edc.oauth.client.id=3A:F4:B9:17:B7:01:BC:4D:A7:8B:58:19:18:30:7F:65:30:BB:90:62:keyid:3A:F4:B9:17:B7:01:BC:4D:A7:8B:58:19:18:30:7F:65:30:BB:90:62
        edc.oauth.public.key.alias=daps-cert-edc-test-provider-dev
        edc.oauth.private.key.alias=daps-cert-key-edc-test-provider-dev
        edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
        edc.oauth.provider.jwks.url=https://daps1.int.demo.catena-x.net/.well-known/jwks.json
        edc.oauth.token.url=https://daps1.int.demo.catena-x.net/token

        edc.vault.hashicorp.url=https://vault.demo.catena-x.net
        edc.vault.hashicorp.token=<path:traceability-foss/data/dev/edc#edc.vault.hashicorp.token>
        edc.vault.hashicorp.timeout.seconds=30
        edc.vault.hashicorp.health.check.enabled=true
        edc.vault.hashicorp.health.check.standby.ok=true
        edc.vault.hashicorp.api.secret.path=/v1/traceability-foss
