image:
  tag: $ARGOCD_APP_REVISION

springprofile: int

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  hosts:
    - host: "traceability.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - "traceability.int.demo.catena-x.net"
      secretName: tls-secret

traceability:
  bpn: "BPNL00000003AYRE"

mailserver:
  host: "smtp.office365.com"
  port: "587"
  username: "notifications@catena-x.net"
  password: <path:traceability-foss/data/int#mailserverPassword>

datasource:
  url: jdbc:postgresql://product-traceability-foss-backend-postgresql:5432/trace
  username: trace
  password: <path:traceability-foss/data/int/database#tracePassword>

oauth2:
  clientId: <path:traceability-foss/data/int/keycloak/oauth2#clientId>
  clientSecret: <path:traceability-foss/data/int/keycloak/oauth2#clientSecret>
  clientTokenUri: "https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
  jwkSetUri: "https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs"
  resourceClient: "Cl17-CX-Part"

edc:
  apiKey: "<path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>"

postgresql:
  enabled: true
  auth:
    postgresPassword: "<path:traceability-foss/data/int/database#postgresPassword>"
    password: "<path:traceability-foss/data/int/database#tracePassword>"
    database: "trace"
    username: "trace"

pgadmin4:
  enabled: true
  strategy:
    type: Recreate
  networkPolicy:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - host: tracex-pgadmin4.int.demo.catena-x.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - tracex-pgadmin4.int.demo.catena-x.net
        secretName: tls-secret
  env:
    email: pgadmin4@trace.foss
    password: "<path:traceability-foss/data/int/database#pgadminPassword>"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

global:
  enablePrometheus: false
  enableGrafana: false

irs-helm:
  enabled: true

  nameOverride: "tracex-irs"
  fullnameOverride: "tracex-irs"

  namespace: product-traceability-foss

  image:
    tag: "1.3.0"

  springprofile: dev

  irsUrl: "https://tracex-irs.int.demo.catena-x.net"

  ingress:
    hosts:
      - host: "tracex-irs.int.demo.catena-x.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - "tracex-irs.int.demo.catena-x.net"
        secretName: tls-secret
  digitalTwinRegistry:
    url: https://semantics.int.demo.catena-x.net/registry
  semanticsHub:
    url: https://semantics.int.demo.catena-x.net/hub/api/v1
  bpdm:
    url: https://catenax-bpdm-int.demo.catena-x.net/v1
  minioUser: <path:traceability-foss/data/int/minio#user>
  minioPassword: <path:traceability-foss/data/int/minio#password>
  keycloak:
    oauth2:
      clientId: <path:traceability-foss/data/int/keycloak/oauth2#clientId>
      clientSecret: <path:traceability-foss/data/int/keycloak/oauth2#clientSecret>
      clientTokenUri: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
      jwkSetUri: https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs

  aasWrapper:
    host: http://product-traceability-foss-backend-irs-aaswrapper:9191/api/service
    username: tracefoss
    password: <path:traceability-foss/data/int/edc/api-wrapper#wrapper.auth.basic.tracefoss>

  minio:
    url: http://tracex-irs-minio:9000

  irs-minio:
    namespace: product-traceability-foss

    minioUser: <path:traceability-foss/data/int/minio#user>
    minioPassword: <path:traceability-foss/data/int/minio#password>

    ## Path where PV would be mounted on the MinIO Pod
    mountPath: "/data"

    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      enabled: false

  # Values for aas wrapper subchart.
  irs-aaswrapper:
    namespace: product-traceability-foss

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts:
        - host: "tracex-irs-aas-wrapper.int.demo.catena-x.net"
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: aaswrapper
                  port:
                    number: 9191
      tls:
        - hosts:
            - "tracex-irs-aas-wrapper.int.demo.catena-x.net"
          # Default secret for certificate creation already provided to your namespace
          secretName: tls-secret

    configuration:
      properties: |-
        web.http.port=9191
        web.http.path=/api
        web.http.callback.port=9192
        web.http.callback.path=/callback
        wrapper.consumer.edc.datamanagement.url=http://tracex-consumer-controlplane:8181/data
        wrapper.consumer.edc.control.url=http://tracex-consumer-controlplane:9999/api/controlplane/control
        wrapper.consumer.edc.apikey.name=X-Api-Key
        wrapper.consumer.edc.apikey.value=<path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>
        wrapper.callback.timeout=120
        wrapper.cache.agreement.enabled=true
        wrapper.auth.basic.tracefoss=<path:traceability-foss/data/int/edc/api-wrapper#wrapper.auth.basic.tracefoss>

  # Values for consumer edc postgres
  postgresql:
    nameOverride: "tracex-consumer-edc-postgresql"
    fullnameOverride: "tracex-consumer-edc-postgresql"

    namespace: product-traceability-foss

    auth:
      postgresPassword: <path:traceability-foss/data/int/edc/database#password>
      username: <path:traceability-foss/data/int/edc/database#user>
      password: <path:traceability-foss/data/int/edc/database#password>
      database: "edc"

  # Values for consumer edc-controlplane.
  edc-controlplane:
    nameOverride: "tracex-consumer-controlplane"
    fullnameOverride: "tracex-consumer-controlplane"

    namespace: product-traceability-foss

    image:
      tag: "0.1.2"

    ingresses:
      - enabled: true
        hostname: "tracex-consumer-controlplane.int.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - ids
          - data
        className: "nginx"
        tls:
          - hosts:
              - "tracex-consumer-controlplane.int.demo.catena-x.net"
            secretName: tls-secret

    resources:
      limits:
        cpu: 1.5
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

    logging:
      # -- EDC logging.properties configuring the [java.util.logging subsystem](https://docs.oracle.com/javase/7/docs/technotes/guides/logging/overview.html#a1.8)
      properties: |-
        .level=INFO
        org.eclipse.dataspaceconnector.level=INFO
        net.catenax.edc.hashicorpvault.level=INFO
        handlers=java.util.logging.ConsoleHandler
        java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
        java.util.logging.ConsoleHandler.level=INFO
        java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n

    configuration:
      # -- EDC configuration.properties configuring aspects of the [eclipse-dataspaceconnector](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector)
      properties: |-
        edc.api.auth.key=<path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>
        ids.webhook.address=https://tracex-consumer-controlplane.int.demo.catena-x.net

        edc.ids.id=urn:connector:edc-consumer-controlplane
        edc.ids.catalog.id=urn:catalog:default
        edc.ids.endpoint=https://tracex-consumer-controlplane.int.demo.catena-x.net/api/v1/ids
        edc.ids.endpoint.audience=https://tracex-consumer-controlplane.int.demo.catena-x.net/api/v1/ids/data

        edc.receiver.http.endpoint=http://product-traceability-foss-backend-test-irs-aaswrapper:9192/callback/endpoint-data-reference

        edc.transfer.dataplane.sync.endpoint=http://tracex-consumer-dataplane:8185/api/public
        edc.transfer.proxy.endpoint=https://tracex-consumer-dataplane.int.demo.catena-x.net/api/public
        edc.transfer.proxy.token.signer.privatekey.alias=token-signer-cert-key-int
        edc.transfer.proxy.token.verifier.publickey.alias=token-signer-cert-int

        edc.dataplane.selector.consumer.url=http://tracex-consumer-dataplane:9999/api/dataplane/control
        edc.dataplane.selector.consumer.sourcetypes=HttpData
        edc.dataplane.selector.consumer.destinationtypes=HttpProxy
        edc.dataplane.selector.consumer.properties={ "publicApiUrl": "https://tracex-consumer-dataplane.int.demo.catena-x.net/api/public" }

        edc.oauth.client.id=D6:DC:B8:0E:8E:A0:DD:EC:03:F9:80:49:88:75:28:72:3C:AE:93:1F:keyid:D6:DC:B8:0E:8E:A0:DD:EC:03:F9:80:49:88:75:28:72:3C:AE:93:1F
        edc.oauth.public.key.alias=daps-cert-int
        edc.oauth.private.key.alias=daps-cert-key-int
        edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
        edc.oauth.provider.jwks.url=https://daps1.int.demo.catena-x.net/.well-known/jwks.json
        edc.oauth.token.url=https://daps1.int.demo.catena-x.net/token

        edc.vault.hashicorp.url=https://vault.demo.catena-x.net
        edc.vault.hashicorp.token=<path:traceability-foss/data/int/edc#edc.vault.hashicorp.token>
        edc.vault.hashicorp.timeout.seconds=30
        edc.vault.hashicorp.health.check.enabled=true
        edc.vault.hashicorp.health.check.standby.ok=true
        edc.vault.hashicorp.api.secret.path=/v1/traceability-foss

        edc.data.encryption.keys.alias=edc-data-encryption-keys-alias
        edc.data.encryption.algorithm=NONE

        # Postgresql related configuration
        edc.datasource.asset.name=asset
        edc.datasource.asset.url=jdbc:postgresql://tracex-consumer-edc-postgresql-hl:5432/edc
        edc.datasource.asset.user=<path:traceability-foss/data/int/edc/database#user>
        edc.datasource.asset.password=<path:traceability-foss/data/int/edc/database#password>
        edc.datasource.contractdefinition.name=contractdefinition
        edc.datasource.contractdefinition.url=jdbc:postgresql://tracex-consumer-edc-postgresql-hl:5432/edc
        edc.datasource.contractdefinition.user=<path:traceability-foss/data/int/edc/database#user>
        edc.datasource.contractdefinition.password=<path:traceability-foss/data/int/edc/database#password>
        edc.datasource.contractnegotiation.name=contractnegotiation
        edc.datasource.contractnegotiation.url=jdbc:postgresql://tracex-consumer-edc-postgresql-hl:5432/edc
        edc.datasource.contractnegotiation.user=<path:traceability-foss/data/int/edc/database#user>
        edc.datasource.contractnegotiation.password=<path:traceability-foss/data/int/edc/database#password>
        edc.datasource.policy.name=policy
        edc.datasource.policy.url=jdbc:postgresql://tracex-consumer-edc-postgresql-hl:5432/edc
        edc.datasource.policy.user=<path:traceability-foss/data/int/edc/database#user>
        edc.datasource.policy.password=<path:traceability-foss/data/int/edc/database#password>
        edc.datasource.transferprocess.name=transferprocess
        edc.datasource.transferprocess.url=jdbc:postgresql://tracex-consumer-edc-postgresql-hl:5432/edc
        edc.datasource.transferprocess.user=<path:traceability-foss/data/int/edc/database#user>
        edc.datasource.transferprocess.password=<path:traceability-foss/data/int/edc/database#password>

  # Values for consumer edc-dataplane.
  edc-dataplane:
    nameOverride: "tracex-consumer-dataplane"
    fullnameOverride: "tracex-consumer-dataplane"

    namespace: product-traceability-foss

    image:
      tag: "0.1.2"

    ingresses:
      - enabled: true
        hostname: "tracex-consumer-dataplane.int.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          - hosts:
              - "tracex-consumer-dataplane.int.demo.catena-x.net"
            secretName: tls-secret

    logging:
      # -- EDC logging.properties configuring the [java.util.logging subsystem](https://docs.oracle.com/javase/7/docs/technotes/guides/logging/overview.html#a1.8)
      properties: |-
        .level=INFO
        org.eclipse.dataspaceconnector.level=INFO
        net.catenax.edc.hashicorpvault.level=INFO
        handlers=java.util.logging.ConsoleHandler
        java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
        java.util.logging.ConsoleHandler.level=INFO
        java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n

    configuration:
      properties: |-
        edc.api.auth.key=<path:traceability-foss/data/int/edc/controlplane#edc.api.control.auth.apikey.value>

        edc.dataplane.token.validation.endpoint=http://tracex-consumer-controlplane:8182/validation/token

        edc.receiver.http.endpoint=http://tracex-irs-aaswrapper:9192/callback/endpoint-data-reference

        edc.oauth.client.id=D6:DC:B8:0E:8E:A0:DD:EC:03:F9:80:49:88:75:28:72:3C:AE:93:1F:keyid:D6:DC:B8:0E:8E:A0:DD:EC:03:F9:80:49:88:75:28:72:3C:AE:93:1F
        edc.oauth.public.key.alias=daps-cert-int
        edc.oauth.private.key.alias=daps-cert-key-int
        edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
        edc.oauth.provider.jwks.url=https://daps1.int.demo.catena-x.net/.well-known/jwks.json
        edc.oauth.token.url=https://daps1.int.demo.catena-x.net/token

        edc.vault.hashicorp.url=https://vault.demo.catena-x.net
        edc.vault.hashicorp.token=<path:traceability-foss/data/int/edc#edc.vault.hashicorp.token>
        edc.vault.hashicorp.timeout.seconds=30
        edc.vault.hashicorp.health.check.enabled=true
        edc.vault.hashicorp.health.check.standby.ok=true
        edc.vault.hashicorp.api.secret.path=/v1/traceability-foss
