apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.frontend.namespace | default .Release.Namespace }}
  name: {{ include "traceability-foss-frontend.fullname" . }}
  labels:
    {{- include "traceability-foss-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.global.frontend.autoscaling.enabled }}
  replicas: {{ .Values.global.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "traceability-foss-frontend.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: 2
  template:
    metadata:
      namespace: {{ .Values.global.frontend.namespace | default .Release.Namespace }}
      {{- with .Values.global.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "traceability-foss-frontend.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- if .Values.global.frontend.imagePullSecret.dockerconfigjson }}
      imagePullSecrets:
        - name: {{ include "traceability-foss-frontend.fullname" . }}-imagepullsecret
      {{- else }}
      {{- with .Values.global.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "traceability-foss-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.global.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.global.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.global.frontend.image.repository }}-frontend:{{ .Values.global.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.frontend.image.pullPolicy }}
          env:
            - name: CATENAX_PORTAL_API_URL
              value: "{{ .Values.global.frontend.image.CATENAX_PORTAL_API_URL }}"
            - name: CATENAX_PORTAL_KEYCLOAK_URL
              value: "{{ .Values.global.frontend.image.CATENAX_PORTAL_KEYCLOAK_URL }}"
            - name: CATENAX_PORTAL_CLIENT_ID
              value: "{{ .Values.global.frontend.image.CATENAX_PORTAL_CLIENT_ID }}"
            - name: CATENAX_PORTAL_BASE_URL
              value: "{{ .Values.global.frontend.image.CATENAX_PORTAL_BASE_URL }}"
            - name: CATENAX_PORTAL_BACKEND_DOMAIN
              value: "{{ .Values.global.frontend.image.CATENAX_PORTAL_BACKEND_DOMAIN }}"
            - name: CATENAX_PORTAL_URL
              value: "{{ .Values.global.frontend.image.CATENAX_PORTAL_URL }}"
          ports:
            - name: http
              containerPort: {{ .Values.global.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.global.frontend.resources | nindent 12 }}
      {{- with .Values.global.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
