{{- if .Values.frontend.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "traceability-foss-frontend.serviceAccountName" . }}
  labels:
    {{- include "traceability-foss-frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
