{{- if .Values.global.backend.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.global.backend.namespace | default .Release.Namespace }}
  name: {{ include "traceability-foss-backend.serviceAccountName" . }}
  labels:
    {{- include "traceability-foss-backend.labels" . | nindent 4 }}
  {{- with .Values.global.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
