style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/catenax-ng/tx-traceability-foss-frontend
options:
  commits:
    filters:
      Type:
        - ftr
        - fix
        - chr
        - doc
        - rfr
        - rev
        - tst
        - wip
  commit_groups:
    title_maps:
      ftr: Features
      fix: Fixes
      chr: Chore
      doc: Documentation
      rfr: Refactoring
      rev: Revert
      tst: Testing Code
      wip: Work In Progress
  header:
    pattern: "^(\\w*)\\:\\s(.*)\\n*(TRACEFOSS-\\d*)?$"
    pattern_maps:
      - Type
      - Subject
      - JiraIssueID
  notes:
    keywords:
      - BREAKING CHANGE
