image:
  tag: $ARGOCD_APP_REVISION
  CATENAX_PORTAL_API_URL: 'https://traceability.dev.demo.catena-x.net/api'
  CATENAX_PORTAL_KEYCLOAK_URL: 'https://centralidp.dev.demo.catena-x.net/auth'
  CATENAX_PORTAL_CLIENT_ID: 'Cl17-CX-Part'
  CATENAX_PORTAL_DEFAULT_REALM: 'CX-Central'

autoscaling:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "traceability-portal.test.dev.demo.catena-x.net"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "traceability-portal.test.dev.demo.catena-x.net"
      secretName: "traceability-portal.test.dev.demo.catena-x.net-tls"
