## Set default rootUser, rootPassword
## AccessKey and secretKey is generated when not set
## Distributed MinIO ref: https://docs.minio.io/docs/distributed-minio-quickstart-guide
##
rootUser: <path:traceability-foss/data/dev/minio#user>
rootPassword: <path:traceability-foss/data/dev/minio#password>

## Path where PV would be mounted on the MinIO Pod
mountPath: "/export"

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: false
