image:
  tag: $ARGOCD_APP_REVISION
  CATENAX_PORTAL_API_URL: 'https://traceability.int.demo.catena-x.net/api'
  CATENAX_PORTAL_KEYCLOAK_URL: 'https://centralidp.int.demo.catena-x.net/auth'
  CATENAX_PORTAL_CLIENT_ID: 'Cl17-CX-Part'
  CATENAX_PORTAL_DEFAULT_REALM: 'CX-Central'
  CATENAX_PORTAL_BACKEND_DOMAIN: 'catena-x.net'

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "traceability-portal.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "traceability-portal.int.demo.catena-x.net"
      secretName: "traceability-portal.int.demo.catena-x.net-tls"
