tractusx-connector:
  enabled: true
  install:
    postgresql: false
    daps: false
    vault: false
  participant:
    id: BPNL00000003CML1

  controlplane:
    ingresses:
      - enabled: false

    endpoints:
      # -- default api for health checks, should not be added to any ingress
      default:
        port: 8080
        path: /api
      # -- data management api, used by internal users, can be added to an ingress and must not be internet facing
      management:
        port: 8081
        path: /management
        # -- authentication key, must be attached to each 'X-Api-Key' request header
        authKey: <path:traceability-foss/data/dev/edc/controlplane#edc.api.control.auth.apikey.value>
      # -- control api, used for internal control calls. can be added to the internal ingress, but should probably not
      control:
        port: 8083
        path: /control
      # -- ids api, used for inter connector communication and must be internet facing
      protocol:
        port: 8084
        path: /api/v1/dsp
      # -- metrics api, used for application metrics, must not be internet facing
      metrics:
        port: 9090
        path: /metrics
      # -- observability api with unsecured access, must not be internet facing
      observability:
        port: 8085
        # -- observability api, provides /health /readiness and /liveness endpoints
        path: /observability
        # -- allow or disallow insecure access, i.e. access without authentication
        insecure: true

    internationalDataSpaces:
      id: TXDC
      description: Tractus-X Eclipse IDS Data Space Connector
      title: ""
      maintainer: ""
      curator: ""
      catalogId: TXDC-Catalog

    # Explicitly declared url for reaching the ids api (e.g. if ingresses not used)
    url:
      ids: ""

    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 2Gi

  dataplane:
    ingresses:
      - enabled: false

    endpoints:
      default:
        port: 8080
        path: /api
      public:
        port: 8081
        path: /api/public
      control:
        port: 8083
        path: /api/dataplane/control
      observability:
        port: 8085
        path: /observability
        insecure: true
      metrics:
        port: 9090
        path: /metrics

    # Explicitly declared url for reaching the public api (e.g. if ingresses not used)
    url:
      public: ""

    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 1Gi

  # URL where the EndpointDataReference callback will be sent to
  backendService:
    httpProxyTokenReceiverUrl: ""

  ################################
  # EDC Vault/DAPS Configuration #
  ################################
  vault:
    hashicorp:
      url: "https://vault.demo.catena-x.net"
      token: "<path:traceability-foss/data/dev/edc#edc.vault.hashicorp.token>"
      timeout: 30
      healthCheck:
        enabled: true
        standbyOk: true
      paths:
        secret: /v1/traceability-foss
        health: /v1/sys/health
    secretNames:
      transferProxyTokenSignerPrivateKey:
      transferProxyTokenSignerPublicKey:
      transferProxyTokenEncryptionAesKey:
      dapsPrivateKey:
      dapsPublicKey:

  daps:
    url: ""
    clientId: ""
    paths:
      jwks: /.well-known/jwks.json
      token: /token

  ##################################
  # EDC Postgres Configuration #
  ##################################
  postgresql:
    enabled: true
    auth:
      username: "<path:traceability-foss/data/dev/edc/database#user>"
      password: "<path:traceability-foss/data/dev/edc/database#password>"
    username: "<path:traceability-foss/data/dev/edc/database#user>"
    password: "<path:traceability-foss/data/dev/edc/database#password>"
    jdbcUrl: "jdbc:postgresql://tracex-edc-provider-edc-postgresql-hl:5432/edc"

##############################
# EDC Postgres Configuration #
##############################
# EDC chart do not support multiple postgres instances in the same namespace at the moment.
# Enable this to use the postgres dependency for when you want to deploy multiple EDC instances in one namespace
edc-postgresql:
  enabled: false
  auth:
    database:
    username:
    postgresPassword:
    password:
