tractusx-connector:
  participant:
    id: BPNL00000003CML1
  enabled: true

  iatp:
    sts:
      oauth:
        client:
          id: <path:traceability-irs/data/dev/controlplane#ssi.oauth.client.id.provider1>
          secret_alias: dev-provider1-miw-secret

  controlplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret

    resources:
      limits:
        cpu: 400m
        memory: 1.5Gi
      requests:
        cpu: 200m
        memory: 1.5Gi

  dataplane:
    token:
      signer:
        privatekey_alias: tracex-dev-daps-cert-provider-key
      verifier:
        publickey_alias: tracex-dev-daps-cert-provider
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-dataplane.dev.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi

  backendService:
    httpProxyTokenReceiverUrl: "https://traceability.dev.demo.catena-x.net/api/callback/endpoint-data-reference"
  postgresql:
    enabled: true
    auth:
      username: "<path:traceability-foss/data/dev/edc/database#user>"
      password: "<path:traceability-foss/data/dev/edc/database#password>"
    username: "<path:traceability-foss/data/dev/edc/database#user>"
    password: "<path:traceability-foss/data/dev/edc/database#password>"
    jdbcUrl: "jdbc:postgresql://tracex-edc-provider-edc-postgresql-hl:5432/edc"
  vault:
    secretNames:
      transferProxyTokenSignerPrivateKey: token-signer-cert-key-dev
      transferProxyTokenSignerPublicKey: token-signer-cert-dev
      transferProxyTokenEncryptionAesKey: token-signer-aes-key

edc-postgresql:
  enabled: true
  auth:
    database: edc
    username: <path:traceability-foss/data/dev/edc/database#user>
    postgresPassword: <path:traceability-foss/data/dev/edc/database#password>
    password: <path:traceability-foss/data/dev/edc/database#password>
