tractusx-connector:
  enabled: true
  nameOverride: "tx-edc-provider-int-a"
  fullnameOverride: "tx-edc-provider-int-a"
  participant:
    id: BPNL00000003CML1
  controlplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-int-a.int.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - protocol
          - management
        tls:
          enabled: true
          secretName: tls-secret
    ssi:
      miw:
        url: <path:traceability-foss/data/int-a/edc/wallet#ssi.miw.url>
        authorityId: <path:traceability-foss/data/int-a/edc/wallet#ssi.miw.authorityId>
      oauth:
        tokenurl: <path:traceability-foss/data/int-a/edc/wallet#ssi.oauth.tokenurl>
        client:
          id: <path:traceability-foss/data/int-a/edc/wallet#ssi.oauth.client.id>
          secretAlias: edc-miw-keycloak-secret-int-a
    endpoints:
      management:
        authKey: <path:traceability-foss/data/int-a/edc/controlplane#edc.api.control.auth.apikey.value>

    resources:
      limits:
        cpu: 400m
        memory: 1.5Gi
      requests:
        cpu: 200m
        memory: 1.5Gi

  dataplane:
    ingresses:
      - enabled: true
        hostname: "trace-x-edc-int-a-dataplane.int.demo.catena-x.net"
        annotations:
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        endpoints:
          - public
        className: "nginx"
        tls:
          enabled: true
          secretName: tls-secret

    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi

  backendService:
    httpProxyTokenReceiverUrl: "https://traceability-int-a.int.demo.catena-x.net/api/callback/endpoint-data-reference"

  postgresql:
    enabled: true
    auth:
      username: "<path:traceability-foss/data/int-a/edc/database#user>"
      password: "<path:traceability-foss/data/int-a/edc/database#password>"
    username: "<path:traceability-foss/data/int-a/edc/database#user>"
    password: "<path:traceability-foss/data/int-a/edc/database#password>"
    jdbcUrl: "jdbc:postgresql://tx-edc-provider-postgresql-int-a-hl:5432/edc"

  vault:
    hashicorp:
      url: "https://vault.demo.catena-x.net"
      token: "<path:traceability-foss/data/int-a/edc#edc.vault.hashicorp.token>"
      timeout: 30
      healthCheck:
        enabled: true
        standbyOk: true
      paths:
        secret: /v1/traceability-foss
        health: /v1/sys/health
    secretNames:
      transferProxyTokenSignerPrivateKey: daps-cert-key-int-a
      transferProxyTokenSignerPublicKey: daps-cert-int-a
      transferProxyTokenEncryptionAesKey: token-signer-aes-key

edc-postgresql:
  nameOverride: "tx-edc-provider-postgresql-int-a"
  fullnameOverride: "tx-edc-provider-postgresql-int-a"
  enabled: true

  primary:
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 200m
        memory: 1Gi
  auth:
    database: edc
    username: <path:traceability-foss/data/int-a/edc/database#user>
    postgresPassword: <path:traceability-foss/data/int-a/edc/database#password>
    password: <path:traceability-foss/data/int-a/edc/database#password>
