name: "[BE][FE][BUILT] Docker Image"

on:
  workflow_dispatch: # Trigger manually
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'

concurrency:
  # cancel older running jobs on the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-image-to-registry:
    strategy:
      fail-fast: false # Prevents the workflow from stopping when a job fails
      matrix:
        config:
          - image_name: "traceability-foss"
            dockerfile_path: "./Dockerfile"
          - image_name: "traceability-foss-frontend"
            dockerfile_path: "./frontend/Dockerfile"
          - image_name: "cfx-traceability-foss-frontend"
            dockerfile_path: "./cfx-frontend/Dockerfile"
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
    name: Central Pipelines (Docker)
    uses: Cofinity-X/central-pipelines/.github/workflows/reusable-publish-image-to-acr.yaml@main
    with:
      team_name: "trace-x"
      repository_name: "traceability-foss"
      service_name: "${{ matrix.config.image_name }}"
      dockerfile_path: "${{ matrix.config.dockerfile_path }}"
      environment: "lower-env-acr"
      push: true
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      PACKAGES_ACCESS_USERNAME: ${{ secrets.PACKAGES_ACCESS_USERNAME }}
      PACKAGES_ACCESS_TOKEN: ${{ secrets.PACKAGES_ACCESS_TOKEN }}

  # To dispatch a workflow in core-services-charts repo for auto image tag update. The following job could be developed as reusable workflow in the future.
  auto-deploy-dispatch:
    needs: push-image-to-registry
    name: Dispatch charts repo workflow
    runs-on: ubuntu-latest
    if: ${{ (github.event_name != 'pull_request') && (github.ref_type != 'tag') }}  # Execute only if container image is pushed and no tag is published
    strategy:
      matrix:
        environment:
          - name: trace-x-a
            helm_values_path: "traceability-foss/int/values-int-a.yaml"
          - name: trace-x-b
            helm_values_path: "traceability-foss/int/values-int-b.yaml"
    steps:
      # Get image tags from the previous job filter the tag that needs to be updated.
      # When triggered by push on main, the tag "main-{sha}" will be used.
      # When triggered manually on a branch, the tag "{branch-name}-{sha}" will be used.
      - name: Get image tag
        id: get_image_tag
        run: |
          IMAGE_TAGS="${{ needs.push-image-to-registry.outputs.image_tags }}"
          EVENT_NAME="${{ github.event_name }}"
          REF_TYPE="${{ github.ref_type }}"

          main_tag=""
          branch_tag=""

          for image_tag in $(echo "$IMAGE_TAGS")
          do
            tag=$(echo $image_tag | cut -d ":" -f2)

            # Check for main tag
            if [[ $tag == main* ]]; then
              main_tag=$tag
            # Check for branch tag
            elif [[ $tag != github* && $tag != main* ]]; then
              branch_tag=$tag
            fi
          done

          # Use the tag of the branch name when the workflow was triggered manually on a branch.
          # This allows to deploy branches for testing.
          if [[ "$EVENT_NAME" == 'workflow_dispatch' && "$REF_TYPE" == 'branch' ]]; then
            image_tag=$branch_tag
          else
            image_tag=$main_tag
          fi

          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT

      # Generate a temporary token using GitHub app
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.TRACE_X_WORKFLOW_TRIGGER_GH_APP_ID }}
          private-key: ${{ secrets.TRACE_X_WORKFLOW_TRIGGER_GH_APP_PRIVATE_KEY }}
          repositories: trace-x-charts
          owner: cofinity-x

      - name: Trigger workflow for ${{ matrix.environment.name }}
        env:
          TOKEN: ${{ steps.get_token.outputs.token }}
          HELM_VALUES_PATH: ${{ matrix.environment.helm_values_path }}
          IMAGE_TAG: ${{ steps.get_image_tag.outputs.image_tag }}
          IMAGE_TAG_PROPERTY: '(.backend.image.tag, .frontend.image.tag, .cfx-frontend.image.tag)'
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Cofinity-X/trace-x-charts/dispatches \
            -d '{
              "event_type": "update_image_tag",
              "client_payload": {
                "image_tag": "${{ env.IMAGE_TAG }}",
                "helm_values_path": "${{ env.HELM_VALUES_PATH }}",
                "image_tag_property": "${{ env.IMAGE_TAG_PROPERTY }}",
                "dispatcher_info": "Runner id - ${{ env.GITHUB_RUN_ID }}"
              }
            }' \
            --fail
