#    Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#    See the NOTICE file(s) distributed with this work for additional
#    information regarding copyright ownership.
#
#    This program and the accompanying materials are made available under the
#    terms of the Apache License, Version 2.0 which is available at
#    https://www.apache.org/licenses/LICENSE-2.0.
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#
#  SPDX-License-Identifier: Apache-2.0

name: "[FE][BUILT][RELEASE] Docker Cofinity-X Image on main & dev"

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'cfx-frontend/**'
  workflow_dispatch:

env:
  IMAGE_PREFIX: cfx
  DOCKERFILE_PATH: ./cfx-frontend/Dockerfile
  IMAGE_REGISTRY: acrcfxsharedservices.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest
    environment: acr-shared-env
    defaults:
      run:
        working-directory: cfx-frontend
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Azure CLI auth
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: az acr login --name ${{ env.IMAGE_REGISTRY }}

      - name: Make organization and repository name lowercase
        run: echo "GITHUB_REPOSITORY_LOWERCASE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker based on trigger event
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.GITHUB_REPOSITORY_LOWERCASE }}-frontend
          tags: |
            type=raw,value=${{ env.IMAGE_PREFIX }}-latest,enable=${{ endsWith(GitHub.ref, 'dev') }}
            type=sha,format=short,prefix=${{ env.IMAGE_PREFIX }}-
            type=ref,event=pr

      - name: Build & Push to image registry ${{ env.IMAGE_REGISTRY }}/${{ env.GITHUB_REPOSITORY_LOWERCASE }}-frontend:${{ steps.short-sha.outputs.sha }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ${{ env.DOCKERFILE_PATH }}
          tags:  ${{ steps.docker_meta.outputs.tags }}
