name: Frontend Build&Push Docker image on main

on:
  push:
    branches: main

env:
  GHCR_REGISTRY: ghcr.io
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_REGISTRY_NAMESPACE: tractusx
  FRONTEND_IMAGE_DOCKER_HUB: traceability-foss-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GHCR Registry
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        if: env.DOCKER_HUB_USER == ''
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR Registry ${{ env.GHCR_REGISTRY }}/${{ github.repository }}-frontend:${{ github.sha }}
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        if: env.DOCKER_HUB_USER == ''
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{ env.GHCR_REGISTRY }}/${{ github.repository }}-frontend:${{ github.sha }}

      - name: Login to Docker Hub
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        if: env.DOCKER_HUB_USER != ''
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push for Docker Hub ${{ env.DOCKER_HUB_REGISTRY_NAMESPACE }}/${{ env.FRONTEND_IMAGE_DOCKER_HUB }}:${{ github.sha }}
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        if: env.DOCKER_HUB_USER != ''
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{ env.DOCKER_HUB_REGISTRY_NAMESPACE }}/${{ env.FRONTEND_IMAGE_DOCKER_HUB }}:${{ github.sha }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        if: env.DOCKER_HUB_USER != ''
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ env.DOCKER_HUB_REGISTRY_NAMESPACE }}/${{ env.FRONTEND_IMAGE_DOCKER_HUB }}
          readme-filepath: README.md
