name: "Publish OpenAPI to Swaggerhub"

on:
  workflow_call:
    inputs:
      version:
        required: true
        description: Version that will be published to Swaggerhub
        type: string

jobs:
  swagger-api:
    runs-on: ubuntu-latest
    env:
      SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
      SWAGGERHUB_USER: ${{ secrets.SWAGGERHUB_USER }}
      SPEC_FILE: docs/api/traceability-foss-backend.json
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get updated OpenAPI spec
        run: git pull

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install Swagger CLI
        run: |
          npm i -g swaggerhub-cli

      - name: Extract versions
        run: |
          export VERSION="${{ inputs.version }}"
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"

      # create API, will fail if exists
      - name: Create API
        continue-on-error: true
        run: |
          swaggerhub api:create ${{ env.SWAGGERHUB_USER }}/trace-x/${{ env.VERSION }} -f ${{ env.SPEC_FILE }} --visibility=public --published=unpublish

      # Post the API to SwaggerHub as "unpublished", because published APIs cannot be overwritten
      - name: Publish API Specs to SwaggerHub
        run: |
          if [[ ${{ env.VERSION }} != *-SNAPSHOT ]]; then
            echo "[INFO] - no snapshot, will set the API to 'published'";
            swaggerhub api:update ${{ env.SWAGGERHUB_USER }}/trace-x/${{ env.VERSION }} -f ${{ env.SPEC_FILE }} --visibility=public --published=publish
            swaggerhub api:setdefault ${{ env.SWAGGERHUB_USER }}/trace-x/${{ env.VERSION }}
          else
            echo "[INFO] - snapshot, will set the API to 'unpublished'";
            swaggerhub api:update ${{ env.SWAGGERHUB_USER }}/trace-x/${{ env.VERSION }} -f ${{ env.SPEC_FILE }} --visibility=public --published=unpublish
          fi
