---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-wrapper.fullname" . }}
  labels:
    {{- include "api-wrapper.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-wrapper.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "api-wrapper.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecret.dockerconfigjson }}
      imagePullSecrets:
        - name: {{ include "api-wrapper.fullname" . }}-imagepullsecret
      {{- else }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "api-wrapper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: EDC_FS_CONFIG
              value: /app/dataspaceconnector-configuration.properties
          {{- if .Values.env }}
          {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          ports:
            - name: default
              containerPort: {{ .Values.edc.endpoints.default.port }}
              protocol: TCP
            - name: callback
              containerPort: {{ .Values.edc.endpoints.callback.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/liveness
              port: default
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/readiness
              port: default
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/startup
              port: default
            failureThreshold: 12
            initialDelaySeconds: 10
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: configuration
              mountPath: /app/dataspaceconnector-configuration.properties
              subPath: dataspaceconnector-configuration.properties
      volumes:
        - name: configuration
          configMap:
            name: {{ include "api-wrapper.fullname" . }}-configmap
            items:
              - key: dataspaceconnector-configuration.properties
                path: dataspaceconnector-configuration.properties
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
